name: CI - Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, pdo, sqlite
          coverage: none

      - name: Copiar arquivo .env
        run: cp .env.example .env

      - name: Instalar dependências
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Gerar APP_KEY
        run: php artisan key:generate

      - name: Criar banco SQLite
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Rodar migrations
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan migrate --force

      - name: Rodar testes
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test
